package com.huy.model.pojo;
// Generated Oct 10, 2015 2:13:18 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Brain generated by hbm2java
 */
public class Brain implements java.io.Serializable {

	private Integer brainId;
	private String brainName;
	private Set<Product> products = new HashSet<Product>(0);

	public Brain() {
	}

	public Brain(String brainName) {
		this.brainName = brainName;
	}

	public Brain(String brainName, Set<Product> products) {
		this.brainName = brainName;
		this.products = products;
	}

	public Integer getBrainId() {
		return this.brainId;
	}

	public void setBrainId(Integer brainId) {
		this.brainId = brainId;
	}

	public String getBrainName() {
		return this.brainName;
	}

	public void setBrainName(String brainName) {
		this.brainName = brainName;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
