package com.huy.model.pojo;
// Generated Oct 10, 2015 2:13:18 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private String email;
	private String date;
	private String statusCart;
	private Set<DetailCart> detailCarts = new HashSet<DetailCart>(0);

	public Cart() {
	}

	public Cart(String email, String date) {
		this.email = email;
		this.date = date;
	}

	public Cart(String email, String date, String statusCart, Set<DetailCart> detailCarts) {
		this.email = email;
		this.date = date;
		this.statusCart = statusCart;
		this.detailCarts = detailCarts;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getStatusCart() {
		return this.statusCart;
	}

	public void setStatusCart(String statusCart) {
		this.statusCart = statusCart;
	}

	public Set<DetailCart> getDetailCarts() {
		return this.detailCarts;
	}

	public void setDetailCarts(Set<DetailCart> detailCarts) {
		this.detailCarts = detailCarts;
	}

}
