package com.huy.model.pojo;
// Generated Oct 10, 2015 2:13:18 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color implements java.io.Serializable {

	private Integer colorId;
	private String colorName;
	private Set<DetailProduct> detailProducts = new HashSet<DetailProduct>(0);

	public Color() {
	}

	public Color(String colorName) {
		this.colorName = colorName;
	}

	public Color(String colorName, Set<DetailProduct> detailProducts) {
		this.colorName = colorName;
		this.detailProducts = detailProducts;
	}

	public Integer getColorId() {
		return this.colorId;
	}

	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}

	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	public Set<DetailProduct> getDetailProducts() {
		return this.detailProducts;
	}

	public void setDetailProducts(Set<DetailProduct> detailProducts) {
		this.detailProducts = detailProducts;
	}

}
