package com.huy.model.pojo;
// Generated Oct 10, 2015 2:13:18 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * DetailProduct generated by hbm2java
 */
public class DetailProduct implements java.io.Serializable {

	private Integer detailProductId;
	private Color color;
	private Product product;
	private Set<DetailCart> detailCarts = new HashSet<DetailCart>(0);

	public DetailProduct() {
	}

	public DetailProduct(Color color, Product product) {
		this.color = color;
		this.product = product;
	}

	public DetailProduct(Color color, Product product, Set<DetailCart> detailCarts) {
		this.color = color;
		this.product = product;
		this.detailCarts = detailCarts;
	}

	public Integer getDetailProductId() {
		return this.detailProductId;
	}

	public void setDetailProductId(Integer detailProductId) {
		this.detailProductId = detailProductId;
	}

	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Set<DetailCart> getDetailCarts() {
		return this.detailCarts;
	}

	public void setDetailCarts(Set<DetailCart> detailCarts) {
		this.detailCarts = detailCarts;
	}

}
