package com.huy.model.pojo;
// Generated Oct 10, 2015 2:13:18 AM by Hibernate Tools 4.3.1

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private Integer imageId;
	private Product product;
	private String imageUrl;

	public Image() {
	}

	public Image(Product product, String imageUrl) {
		this.product = product;
		this.imageUrl = imageUrl;
	}

	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}
