package com.huy.model.pojo;
// Generated Oct 10, 2015 2:13:18 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private Brain brain;
	private String productName;
	private float price;
	private float sizeScreen;
	private String img;
	private Set<DetailProduct> detailProducts = new HashSet<DetailProduct>(0);
	private Set<Image> images = new HashSet<Image>(0);

	public Product() {
	}

	public Product(Brain brain, String productName, float price, float sizeScreen, String img) {
		this.brain = brain;
		this.productName = productName;
		this.price = price;
		this.sizeScreen = sizeScreen;
		this.img = img;
	}

	public Product(Brain brain, String productName, float price, float sizeScreen, String img,
			Set<DetailProduct> detailProducts, Set<Image> images) {
		this.brain = brain;
		this.productName = productName;
		this.price = price;
		this.sizeScreen = sizeScreen;
		this.img = img;
		this.detailProducts = detailProducts;
		this.images = images;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Brain getBrain() {
		return this.brain;
	}

	public void setBrain(Brain brain) {
		this.brain = brain;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public float getSizeScreen() {
		return this.sizeScreen;
	}

	public void setSizeScreen(float sizeScreen) {
		this.sizeScreen = sizeScreen;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public Set<DetailProduct> getDetailProducts() {
		return this.detailProducts;
	}

	public void setDetailProducts(Set<DetailProduct> detailProducts) {
		this.detailProducts = detailProducts;
	}

	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
